services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  hardhat:
    build:
      context: ./packages/contracts
      dockerfile: Dockerfile.hardhat
    ports:
      - "8545:8545"
    volumes:
      - ./packages/contracts:/app
      - /app/node_modules

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017
      - REDIS_URL=redis://redis:6379
      - ETHEREUM_RPC_URL=http://hardhat:8545
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - CONTRACT_ADDRESS=
    depends_on:
      - mongodb
      - redis
      - hardhat

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  monitoring-node-1:
    build:
      context: ./packages/monitoring-node
      dockerfile: Dockerfile
    environment:
      - NODE_ID=1
      - BACKEND_URL=http://backend:3001
      - ETHEREUM_RPC_URL=http://hardhat:8545
    depends_on:
      - backend
      - hardhat

  monitoring-node-2:
    build:
      context: ./packages/monitoring-node
      dockerfile: Dockerfile
    environment:
      - NODE_ID=2
      - BACKEND_URL=http://backend:3001
      - ETHEREUM_RPC_URL=http://hardhat:8545
    depends_on:
      - backend
      - hardhat

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./packages/frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./packages/frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend

volumes:
  mongodb_data: